### ISSUE TITLE
Misunderstanding when using typescript

### ISSUE THREAD

**Issue by levchak0910** [andrewcourtice/harlem#16]
Hi, @andrewcourtice 
I am tring to use your state manager and am stuck with some misunderstanding
(I am not very proficient in typescript)

Could you explain why I see this type error?
![1](https://user-images.githubusercontent.com/37511777/98082060-ceda6b00-1e80-11eb-9c00-bbfb30056aee.png)

codebase is [here](https://github.com/mutoe/vue3-realworld-example-app/tree/use-harlem)

**Comment by andrewcourtice** [comment]
Hi @levchak0910 - the reason you are seeing the above error is because `user.value` could be null based on the type you have specified for your state structure.

To resolve this you would need to do a null check before accessing the `username` property of the user either in the computed of your component or in the user getter itself.

Hopefully that helps :)

**Comment by levchak0910** [comment]
Type checking I have by `checkAuthorization(user)` which return me that user is not `null` 
I just can't figure out why the place of destructuring affects the type checking
(In the right part types are ok)

**Comment by levchak0910** [comment]
It seems like typescript is not sure, if user.value will be of type User after running setup (in setup function's scope, even after user defined guard). Because setup could be async and when it run, user.value could be another type (null) - that why error on left side
At least that's how I understood
Related typescript issues: [1](https://github.com/Microsoft/TypeScript/issues/18620), [2](https://github.com/microsoft/TypeScript/issues/39340), [main thread](https://github.com/microsoft/TypeScript/issues/11498)
