### ISSUE TITLE
Module parse failed: Unexpected token (112:19)

### ISSUE THREAD

**Issue by Dzelix** [andrewcourtice/harlem#35]
I have a problem with Harlem when I use Vue CLI boilerplate.

The compilation error is following:

```
ERROR  Failed to compile with 1 error
error  in ./node_modules/@harlem/core/dist/esm/index.js
Module parse failed: Unexpected token (112:19)
```

```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       providers: {
|         ...PROVIDERS,
>         ...options?.providers
|       }
|     };

```

```
 @ ./src/main.js 7:0-34 8:19-25
 @ multi (webpack)-dev-server/client?http://192.168.1.69:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js`
```

Steps to reproduce the behaviour:
1. Use `vue create app` to create vue project.
2. Install Harlem with NPM.
3. Add `import Harlem from '@harlem/core';` and `createApp(App).use(Harlem).mount('#app')` to main.js file.
4. Run npm run serve to compile the project.
5. Have aforementioned error.

Version:
1. Harlem: ^2.0.0
2. Vue: ^3.0.0
3. "@vue/cli-plugin-babel": "~4.5.0",
4. "@vue/cli-plugin-eslint": "~4.5.0",
5. "@vue/cli-service": "~4.5.0",

**Comment by andrewcourtice** [comment]
Hi @Dzelix 

This error is due to Harlem using modern language features such as optional chaining etc. These features are only available in ES2020. I have changed Harlem's target browser version to match Vue 3's target browser version which is ES2016.

This issue should now be fixed in v2.0.1.

I also noticed that your target Vue version is `^3.0.0`. Harlem `^2.0.0` requires at least version `^3.2.0` of Vue as it uses new features only available in Vue 3.2.

Let me know if v2.0.1 fixes the issue.

Thanks
